"""Narrative trait models and tier calculations for QuestForge."""
from enum import Enum
from typing import Any
from pydantic import BaseModel, Field, model_validator


class TraitTier(str, Enum):
    NONE = "none"
    EMERGING = "emerging"
    ESTABLISHED = "established"
    DOMINANT = "dominant"


def count_to_tier(count: int) -> TraitTier:
    """Derive TraitTier from the number of trait-tagged choices picked."""
    if count >= 8:
        return TraitTier.DOMINANT
    if count >= 4:
        return TraitTier.ESTABLISHED
    if count >= 1:
        return TraitTier.EMERGING
    return TraitTier.NONE


def tier_to_min_count(tier: TraitTier | str) -> int:
    """Derive minimum choice count required to satisfy a TraitTier."""
    t_val = tier.value if hasattr(tier, "value") else str(tier).lower()
    mapping = {
        "none": 0,
        "emerging": 1,
        "established": 4,
        "dominant": 8,
    }
    return mapping.get(t_val, 1)


class TraitDefinition(BaseModel):
    """Definition of one of the emergent traits (maximum 2 per story)."""
    name: str = Field(description="Trait name, e.g. 'Cunning', 'Compassion'")
    description: str = Field(description="One-sentence description of what this trait represents")
    color_hex: str = Field(
        default="#E0A82E",
        description="Hex colour used to display this trait in the Designer UI",
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_keys(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if "name" not in data and "trait_name" in data:
                data["name"] = data["trait_name"]
            if "color_hex" not in data and "hex_color" in data:
                data["color_hex"] = data["hex_color"]
            if "color_hex" not in data and "color" in data:
                data["color_hex"] = data["color"]
        return data


class TraitRequirement(BaseModel):
    """A requirement condition for gating dialogue choices or quests."""
    name: str = Field(description="The trait name required")
    strength: TraitTier = Field(
        default=TraitTier.EMERGING,
        description="Minimum tier required: 'emerging', 'established', 'dominant'",
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_trait_requirement(cls, data: Any) -> Any:
        if isinstance(data, dict):
            # Normalize trait name
            if "name" not in data and "trait_name" in data:
                data["name"] = data["trait_name"]
            if "name" not in data and "trait" in data:
                data["name"] = data["trait"]

            # Normalize strength
            strength = data.get("strength")
            if isinstance(strength, str):
                s_lower = strength.lower().strip()
                strength_map = {
                    "none": TraitTier.NONE,
                    "emerging": TraitTier.EMERGING,
                    "established": TraitTier.ESTABLISHED,
                    "dominant": TraitTier.DOMINANT,
                    # Common variations from LLM outputs
                    "low": TraitTier.EMERGING,
                    "weak": TraitTier.EMERGING,
                    "minor": TraitTier.EMERGING,
                    "moderate": TraitTier.ESTABLISHED,
                    "medium": TraitTier.ESTABLISHED,
                    "mid": TraitTier.ESTABLISHED,
                    "high": TraitTier.DOMINANT,
                    "strong": TraitTier.DOMINANT,
                    "max": TraitTier.DOMINANT,
                    "major": TraitTier.DOMINANT,
                }
                data["strength"] = strength_map.get(s_lower, TraitTier.EMERGING)
            elif strength is None:
                data["strength"] = TraitTier.EMERGING
        return data


class TraitSnapshot(BaseModel):
    """Snapshot of player trait progression at a given point or chapter boundary."""
    traits: dict[str, TraitTier] = Field(
        default_factory=dict,
        description="Map of trait_name to current tier",
    )
    raw_counts: dict[str, int] = Field(
        default_factory=dict,
        description="Map of trait_name to cumulative choice count",
    )

    def set_choice_count(self, trait_name: str, count: int) -> None:
        self.raw_counts[trait_name] = count
        self.traits[trait_name] = count_to_tier(count)


class TraitArcValidation(BaseModel):
    """Validation report generated by the Quest Architect for trait gating reachability."""
    is_valid: bool = Field(default=True)
    warnings: list[str] = Field(default_factory=list)
    max_reachable_counts: dict[str, int] = Field(default_factory=dict)
    unreachable_gates: list[str] = Field(default_factory=list)
